"""updated tables to reflect latest changes

Revision ID: 63c6e70e03eb
Revises: 1c532f2adeee
Create Date: 2024-08-22 15:03:44.179656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c6e70e03eb'
down_revision: Union[str, None] = '1c532f2adeee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_product_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'product_id')
    op.drop_column('orders', 'quantity')
    op.add_column('products', sa.Column('order_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'products', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'order_id')
    op.add_column('orders', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('orders_product_id_fkey', 'orders', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
